#!/bin/bash

version=$1

dir=$(echo zabbix-$version)

branch=$(echo $version|grep -E -o "^[0-9]\.[0-9]")

listen=$(echo $branch|sed "s|\.||g;s|^|1|")

zcode=$(echo $branch|sed "s|\.||g;s|^|z|")

bport=$(echo $branch|sed "s|\.||g;s|^|1|;s|$|51|")

echo version=$version
echo dir=$dir
echo branch=$branch
echo zcode=$zcode

grep "$dir" /etc/nginx/conf.d/http.$zcode.aigarskadikis.com.$listen.conf 
if [ $? -ne 0 ]; then

    # if this version is currently not configured in nginx conf
    if [ ! -d "/usr/share/$dir" ]; then

        echo "/usr/share/$dir" not exists

        git clone https://git.zabbix.com/scm/zbx/zabbix.git --branch $version --depth 1 --single-branch /usr/share/$dir
        if [ $? -ne 0 ]; then
            echo this branch does not exists
        else
            echo the clone went successfully. installing frontend config

echo "$branch" | grep "^[5-9]"
if [ $? -ne 0 ]; then

echo setup frontend configuration for 4.4 and lower

cat << EOF > /usr/share/$dir/frontends/php/conf/zabbix.conf.php
<?php
// Zabbix GUI configuration file.
global \$DB;

\$DB['TYPE']     = 'POSTGRESQL';
\$DB['SERVER']   = '10.133.112.87';
\$DB['PORT']     = '7412';
\$DB['DATABASE'] = '$zcode';
\$DB['USER']     = 'zabbix';
\$DB['PASSWORD'] = 'zabbix';

// Schema name. Used for IBM DB2 and PostgreSQL.
\$DB['SCHEMA'] = 'public';

\$ZBX_SERVER      = '10.133.253.44';
\$ZBX_SERVER_PORT = '$bport';
\$ZBX_SERVER_NAME = '';

\$IMAGE_FORMAT_DEFAULT = IMAGE_FORMAT_PNG;
EOF



echo creating nginx conf
            
cat << EOF > /etc/nginx/conf.d/http.$zcode.aigarskadikis.com.$listen.conf
server {
        listen          $listen;
        server_name     $zcode.aigarskadikis.com;

        root    /usr/share/$dir/frontends/php;

        index   index.php;

        location = /favicon.ico {
                log_not_found   off;
        }

        location / {
                try_files       \$uri \$uri/ =404;
        }

        location /assets {
                access_log      off;
                expires         10d;
        }

        location ~ /\.ht {
                deny            all;
        }

        location ~ /(api\/|conf[^\.]|include|locale) {
                deny            all;
                return          404;
        }

        location ~ [^/]\.php(/|$) {
                fastcgi_pass    unix:/run/php-fpm/zabbix.sock;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_index   index.php;

                fastcgi_param   DOCUMENT_ROOT   /usr/share/$dir/frontends/php;
                fastcgi_param   SCRIPT_FILENAME /usr/share/$dir/frontends/php\$fastcgi_script_name;
                fastcgi_param   PATH_TRANSLATED /usr/share/$dir/frontends/php\$fastcgi_script_name;

                include fastcgi_params;
                fastcgi_param   QUERY_STRING    \$query_string;
                fastcgi_param   REQUEST_METHOD  \$request_method;
                fastcgi_param   CONTENT_TYPE    \$content_type;
                fastcgi_param   CONTENT_LENGTH  \$content_length;

                fastcgi_intercept_errors        on;
                fastcgi_ignore_client_abort     off;
                fastcgi_connect_timeout         60;
                fastcgi_send_timeout            9180;
                fastcgi_read_timeout            9180;
                fastcgi_buffer_size             128k;
                fastcgi_buffers                 4 256k;
                fastcgi_busy_buffers_size       256k;
                fastcgi_temp_file_write_size    256k;
        }
        location = /basic_status {
                stub_status;
        }
}
EOF

else
echo setup frontend configuration for 5.0 and uper

cat << EOF > /usr/share/$dir/ui/conf/zabbix.conf.php
<?php
// Zabbix GUI configuration file.
global \$DB;

\$DB['TYPE']     = 'POSTGRESQL';
\$DB['SERVER']   = '10.133.112.87';
\$DB['PORT']     = '7412';
\$DB['DATABASE'] = '$zcode';
\$DB['USER']     = 'zabbix';
\$DB['PASSWORD'] = 'zabbix';

// Schema name. Used for IBM DB2 and PostgreSQL.
\$DB['SCHEMA'] = 'public';

\$ZBX_SERVER      = '10.133.253.44';
\$ZBX_SERVER_PORT = '$bport';
\$ZBX_SERVER_NAME = '';

\$IMAGE_FORMAT_DEFAULT = IMAGE_FORMAT_PNG;
EOF

chmod o+w /usr/share/$dir/ui/conf/zabbix.conf.php
            
cat << EOF > /etc/nginx/conf.d/http.$zcode.aigarskadikis.com.$listen.conf
server {
        listen          $listen;
        server_name     $zcode.aigarskadikis.com;

        root    /usr/share/$dir/ui;

        index   index.php;

        location = /favicon.ico {
                log_not_found   off;
        }

        location / {
                try_files       \$uri \$uri/ =404;
        }

        location /assets {
                access_log      off;
                expires         10d;
        }

        location ~ /\.ht {
                deny            all;
        }

        location ~ /(api\/|conf[^\.]|include|locale) {
                deny            all;
                return          404;
        }

        location ~ [^/]\.php(/|$) {
                fastcgi_pass    unix:/run/php-fpm/zabbix.sock;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_index   index.php;

                fastcgi_param   DOCUMENT_ROOT   /usr/share/$dir/ui;
                fastcgi_param   SCRIPT_FILENAME /usr/share/$dir/ui\$fastcgi_script_name;
                fastcgi_param   PATH_TRANSLATED /usr/share/$dir/ui\$fastcgi_script_name;

                include fastcgi_params;
                fastcgi_param   QUERY_STRING    \$query_string;
                fastcgi_param   REQUEST_METHOD  \$request_method;
                fastcgi_param   CONTENT_TYPE    \$content_type;
                fastcgi_param   CONTENT_LENGTH  \$content_length;

                fastcgi_intercept_errors        on;
                fastcgi_ignore_client_abort     off;
                fastcgi_connect_timeout         60;
                fastcgi_send_timeout            180;
                fastcgi_read_timeout            180;
                fastcgi_buffer_size             128k;
                fastcgi_buffers                 4 256k;
                fastcgi_busy_buffers_size       256k;
                fastcgi_temp_file_write_size    256k;
        }
}
EOF


fi

systemctl restart nginx php-fpm

        fi



    else
        echo need to only change nginx conf
        sed -i "s|zabbix-$branch\.[0-9a-z]\+|$dir|" /etc/nginx/conf.d/http.$zcode.aigarskadikis.com.$listen.conf
systemctl restart nginx php-fpm
    fi

else
    echo already exists on version $version
fi

